# Generated by Django 5.2.4 on 2025-07-08 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_candidateprofile_department_employee_and_more'),
        ('resume_versions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesummary',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='profiles.candidateprofile'),
        ),
    ]
