# Generated by Django 4.2.23 on 2025-07-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_department_candidateprofile_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='location',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='manager',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='team',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Department',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=10),
        ),
    ]
