# Generated by Django 4.2.23 on 2025-07-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_candidateprofile_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='department',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_image',
            field=models.ImageField(default=None, upload_to='my_images/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
