# Generated by Django 4.2.23 on 2025-07-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_candidateprofile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='my_images/'),
        ),
    ]
